클린 코드 리팩토링 작업(dto, mapper)
f-lab-edu/dev-link-central pull request #85
Opened 2024-04-20 15:03 UTC by mingseok

request, response, dto, mapper 분리 작업

2024-04-20 22:38 UTC, seonwoo960000 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-tomcat'
요 의존성은 왜 필요하죠?? 🤔

2024-04-22 13:31 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/database/repository/FriendRepository.java
> +    boolean existsBySenderAndReceiverOrReceiverAndSender(Member sender, Member receiver,
요렇게 복잡한 메서드는 @Query를 사용해보는건 어때요? 
```java
@Query("""
        SELECT count(*) > 0 
        FROM Friend f  
        Where (f.sender = .. AND f.receiver = ..) OR (f.receiver = .. AND f.sender = ..) 
        """)
```

2024-04-22 13:34 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/presentation/dto/ArticleCommentDTO.java
> +public class ArticleCommentDTO {
DTO 클래스는 service package에 포함돼야하는거 아닌가요?

2024-04-22 13:35 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/service/StudyGroupService.java
> +import dev.linkcentral.presentation.dto.request.studygroup.StudyGroupWithMembersRequest;
여전히 service 레이어에서 presentation 레이어를 참조하는 것 같습니다.

2024-04-22 13:36 UTC, seonwoo960000 requested changes

2024-04-22 13:36 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/service/ProfileService.java
> +import dev.linkcentral.presentation.dto.ProfileDetailsDTO;
여전히 service 레이어에서 presentation 레이어를 참조하는 것 같습니다.

2024-04-22 13:36 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/service/MemberService.java
> +import dev.linkcentral.presentation.dto.MemberEditDTO;
여전히 service 레이어에서 presentation 레이어를 참조하는 것 같습니다.

2024-04-22 13:36 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/service/FriendService.java
> +import dev.linkcentral.presentation.dto.FriendRequestDTO;
여전히 service 레이어에서 presentation 레이어를 참조하는 것 같습니다.

2024-04-22 13:36 UTC, seonwoo960000 commented on src/main/java/dev/linkcentral/service/ArticleService.java
> +import dev.linkcentral.presentation.dto.*;
여전히 service 레이어에서 presentation 레이어를 참조하는 것 같습니다.

2024-05-02 17:25 UTC, mingseok commented on src/main/java/dev/linkcentral/database/repository/FriendRepository.java
> +    boolean existsBySenderAndReceiverOrReceiverAndSender(Member sender, Member receiver,
@Query 애노테이션을 사용하는걸 생각하지 못했었네요! 알려주셔서 감사합니다!

2024-05-02 17:25 UTC, mingseok commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-tomcat'
수정하였습니다!

2024-05-02 17:26 UTC, mingseok commented on src/main/java/dev/linkcentral/presentation/dto/ArticleCommentDTO.java
> +public class ArticleCommentDTO {
서비스 패키지로 이동하였습니다!

2024-05-03 08:50 UTC, mingseok commented on src/main/java/dev/linkcentral/service/ProfileService.java
> +import dev.linkcentral.presentation.dto.ProfileDetailsDTO;
수정하였습니다!

2024-05-03 12:10 UTC, seonWKim commented
수고하셨습니다. 아키텍처가 잡혀가는 느낌이네요 ~ 나중에 기회가 되면 archunit 테스트도 적용해보면 좋을 것 같습니다.

2024-05-03 12:11 UTC, seonWKim approved these changes

2024-05-03 12:17 UTC, merged